# Generated by Django 3.1.5 on 2021-04-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fav',
            field=models.BooleanField(default=True),
        ),
    ]
